### ISSUE TITLE
A clearer grunt-browserify example

### ISSUE THREAD

**Issue by angelogulina** [mailmojo/hoganify#3]
I'm trying too hard to make this work and I can't seem to get it right.
Could you put a more elaborate example?

Also, can I require a <code>.mustache</code> template containing HTML?

Thank you.

**Comment by fdanielsen** [comment]
I'm not sure how much clearer the examples could be. You know how to use browserify with grunt, right? And how browserify works? Please tell me what is giving you trouble and I'll see what if anything could be improved on in the examples.

And yes, you can require `.mustache` templates containing HTML, that is very much the point. mustache is a template syntax mostly used with HTML.

**Comment by angelogulina** [comment]
Thank you very much for the reply.
I noticed I wasn't clear myself in the request: I was referring to the <code>grunt-browserify</code> example, in particular.

I have this set in my <code>Gruntfile.js</code>:

<pre>
[ ... ]
browserify: {
     js: {
          src: ['./src/js/app/main.js'],
          dest: 'src/js/app.js'
     },
     options: {
         transform: ['hoganify']
     }
},
[ ... ]
</pre>

Starting the task, this is the error I get on the Term:

> > Running "browserify:js" (browserify) task
> > [ ... ]/templates/navigationItem.mustache:1
> > < a class="button button--rounded" href="#" >
> > ^
> > ParseError: Unexpected token

(Don't mind the space in the tag, I added 'cause I didn't figure out how to not make the link tag act as a link here.)

Since I'm sure there is something wrong in my settings, I was asking for a more elaborate example that could guide me in the details. Of course, I googled for hours before bothering you here :-)

**Comment by fdanielsen** [comment]
Sorry for not getting back to you sooner. Your setup looks correct, so I'm surprised it fails like that. Could you send me the browserify version your using, and the contents of that `.mustache` template it fails on? Though it does look like the hoganify transform is simply not running.

By the way, a suggestion that is beside the issue here, but I'd advice you to set the destination of the built file outside of `src/` :)

**Comment by AngeloGulina** [comment]
Hi, sorry for the late answer.
I'm using grunt-browserify <code>3.4.0</code> which uses browserify <code>9.0.3</code>.
The template is
<code>
< a class="button button--rounded" href="#" >
	< i class="fa fa-{{ icn_name }}" ><  /i >
	< span class="active-title" >{{ btn_name }}< /span >
	< span class="off-title" >{{ btn_shortname }}< /span >
< /a >
</code>

**Comment by angelogulina** [comment]
Hi, sorry for the late answer.
I'm using grunt-browserify <code>3.4.0</code> which uses browserify <code>9.0.3</code>.
The template is

``` html
<a class="button button--rounded" href="#">
    <i class="fa fa-{{ icn_name }}"></i>
    <span class="active-title">{{ btn_name }}</span>
    <span class="off-title">{{ btn_shortname }}</span>
</a>
```

Thank you very much for your support.

**Comment by angelogulina** [comment]
Hello again.
It turns out the problem is with folder's structure and not in the plugin (precisely this: https://github.com/andreypopp/reactify#troubleshooting). Took me forever to solve it.

I thought I was missing something in the configuration but I wasn't.
Thanks again for the support.

**Comment by fdanielsen** [comment]
Hi,

Thanks for your update and the useful information. I'm glad you found a solution to your problems.
